server:
  port: 8070



eureka:
  instance:
    hostname: client
    ip-address: ${spring.cloud.client.ip-address}
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true #是否注册eureka，客户端需要配置
    fetch-registry: true  #是否获取注册表，客户端需要配置
spring:
  application:
    name: client
  cloud:
