server:
  port: 8070



eureka:
  instance:
    hostname: client
    ip-address: ${spring.cloud.client.ip-address} #服务器的IP地址
    preferIpAddress: true #修改注册表中的status值
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #修改注册表中的status值
    #status-page-url-path: ${eureka.instance.instance-id}/custom #状态路径更改，默认情况下时/info
    #health-check-url: 检查心跳的地址
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true #是否注册eureka，客户端需要配置
    fetch-registry: true  #是否获取注册表，客户端需要配置
    enabled: true #是否被服务发现
    healthcheck:
      enabled: true #健康检查
spring:
  application:
    name: client
