server:
  port: 8761

eureka:
  instance:
    hostname: eurekaServer1
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-server